# Generated by Django 5.1.2 on 2024-11-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupportSprint', '0002_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
