# Generated by Django 5.1.2 on 2024-11-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskhelp.department')),
                ('users', models.ManyToManyField(related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Bez tytułu', verbose_name='Tytuł zgłoszenia')),
                ('reporter', models.CharField(max_length=50, verbose_name='Zgłaszający')),
                ('content', models.TextField(max_length=10000, verbose_name='Treść')),
                ('status', models.CharField(choices=[('Nowy', 'Nowy'), ('W trakcie', 'W trakcie'), ('Zakończony', 'Zakończony'), ('Zamknięty', 'Zamknięty'), ('Odrzucony', 'Odrzucony'), ('Zamrożony', 'Zamrożony'), ('Nieaktywny', 'Nieaktywny')], default='Nowy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deskhelp.queue')),
            ],
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='deskhelp.ticket')),
            ],
        ),
    ]
