# Generated by Django 5.1.2 on 2024-12-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskhelp', '0002_department_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deskhelp.queue', verbose_name='Kolejka'),
        ),
    ]
