# Generated by Django 5.0.3 on 2024-05-14 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Bez tytułu",
                        max_length=99999,
                        verbose_name="ticket_title",
                    ),
                ),
                (
                    "reporter",
                    models.EmailField(max_length=254, verbose_name="ticket_reporter"),
                ),
                (
                    "content",
                    models.TextField(max_length=99999, verbose_name="ticket_content"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Nowy", "Nowy"),
                            ("W trakcie", "W trakcie"),
                            ("Zakończony", "Zakończony"),
                            ("Zamknięty", "Zamknięty"),
                            ("Odrzucony", "Odrzucony"),
                            ("Zamrożony", "Zamrożony"),
                            ("Nieaktywny", "Nieaktywny"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default="Niepobrany",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
