# Generated by Django 5.0.3 on 2024-05-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="content",
            field=models.TextField(max_length=10000, verbose_name="ticket_content"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default="Nowy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reporter",
            field=models.EmailField(max_length=254, verbose_name="Zgłaszający"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                default="Bez tytułu", max_length=255, verbose_name="Tytuł zgłoszenia"
            ),
        ),
    ]
