# Generated by Django 5.0.3 on 2024-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0006_alter_ticket_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="content",
            field=models.TextField(max_length=10000, verbose_name="Treść"),
        ),
    ]
