# Generated by Django 5.0.3 on 2024-05-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0009_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
