# Generated by Django 5.0.3 on 2024-05-24 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0011_alter_ticket_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=(),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Nowy", "Nowy"),
                    ("W trakcie", "W trakcie"),
                    ("Zakończony", "Zakończony"),
                    ("Zamknięty", "Zamknięty"),
                    ("Odrzucony", "Odrzucony"),
                    ("Zamrożony", "Zamrożony"),
                    ("Nieaktywny", "Nieaktywny"),
                ],
                default="Nowy",
                max_length=20,
            ),
        ),
    ]
