# Generated by Django 5.0.3 on 2024-05-24 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0014_alter_ticket_reporter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
