# Generated by Django 5.0.3 on 2024-05-24 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskhelp", "0015_queue_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="user",
        ),
        migrations.AddField(
            model_name="queue",
            name="users",
            field=models.ManyToManyField(
                related_name="queues", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
